import { Ride } from './types';

// Collection of beautiful nature and flower images (Indian context friendly)
// Using verified, high-availability Unsplash IDs
export const GARDEN_AVATARS = [
  "https://images.unsplash.com/photo-1490750967868-bcdf92dd218a?w=400&h=400&fit=crop&q=80", // Golden Wheat
  "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=400&h=400&fit=crop&q=80", // Pink Cosmos
  "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=400&fit=crop&q=80", // Beach
  "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=400&fit=crop&q=80", // Forest
  "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=400&h=400&fit=crop&q=80", // Foggy Forest
  "https://images.unsplash.com/photo-1501854140884-074bf86ee911?w=400&h=400&fit=crop&q=80", // Mountains
  "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400&h=400&fit=crop&q=80", // Succulent
  "https://images.unsplash.com/photo-1589140417637-d2054df3a1b5?w=400&h=400&fit=crop&q=80", // Tea Garden
  "https://images.unsplash.com/photo-1552083855-6d309191d511?w=400&h=400&fit=crop&q=80", // Lotus-ish
  "https://images.unsplash.com/photo-1562690868-60bbe7293e94?w=400&h=400&fit=crop&q=80", // Red Flower
  "https://images.unsplash.com/photo-1596238865662-7945d81b4f2c?w=400&h=400&fit=crop&q=80", // Garden
  "https://images.unsplash.com/photo-1560717845-968823efbee1?w=400&h=400&fit=crop&q=80"  // Pink Flower
];

export const SAMPLE_RIDES: Ride[] = [
  {
    id: "r_demo_1",
    hostId: "h_demo_1",
    name: "Ishaan Verma",
    car: "Tata Tiago EV",
    vehicleType: "Hatchback",
    price: 45,
    seatsLeft: 2,
    avatar: GARDEN_AVATARS[11],
    eta: "3 min",
    badge: "Top Rated ⭐",
    from: "Sector 18, Noida",
    to: "Mayur Vihar Phase 1",
    date: new Date().toISOString(),
    time: "17:45",
    rating: 5.0,
  },
  {
    id: "r_demo_2",
    hostId: "h_demo_2",
    name: "Meera Reddy",
    car: "Royal Enfield Classic",
    vehicleType: "Bike",
    price: 80,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[8],
    eta: "12 min",
    badge: "Safe Ride 🛡️",
    from: "Indiranagar",
    to: "Koramangala",
    date: new Date().toISOString(),
    time: "08:30",
    rating: 4.9,
  },
  {
    id: "r1",
    hostId: "h1",
    name: "Rahul Roy",
    car: "Hyundai Creta",
    vehicleType: "SUV",
    price: 45,
    seatsLeft: 3,
    avatar: GARDEN_AVATARS[0],
    eta: "15 min",
    badge: "Daily Commuter 🏢",
    from: "Jamuria",
    to: "Asansol Station",
    date: new Date().toISOString(),
    time: "09:00",
    rating: 4.8,
  },
  {
    id: "r2",
    hostId: "h2",
    name: "Priya Banerjee",
    car: "Maruti Swift",
    vehicleType: "Hatchback",
    price: 60,
    seatsLeft: 2,
    avatar: GARDEN_AVATARS[1],
    eta: "10 min",
    badge: "Verified ✅",
    from: "Asansol City Bus Stand",
    to: "Chittaranjan",
    date: new Date().toISOString(),
    time: "17:30",
    rating: 4.9,
  },
  {
    id: "r3",
    hostId: "h3",
    name: "Amit Kumar",
    car: "Ola S1 Pro",
    vehicleType: "EV Scooty",
    price: 20,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[2],
    eta: "5 min",
    badge: "Eco Friendly 🍃",
    from: "Asansol Court",
    to: "Salanpur",
    date: new Date().toISOString(),
    time: "10:15",
    rating: 4.7,
  },
  {
    id: "r4",
    hostId: "h4",
    name: "Suresh Mondal",
    car: "Mahindra Bolero",
    vehicleType: "SUV",
    price: 80,
    seatsLeft: 4,
    avatar: GARDEN_AVATARS[3],
    eta: "20 min",
    badge: "Heavy Luggage 🧳",
    from: "Raniganj",
    to: "Durgapur City Centre",
    date: new Date().toISOString(),
    time: "08:00",
    rating: 4.6,
  },
  {
    id: "r5",
    hostId: "h5",
    name: "Anjali Das",
    car: "Honda Amaze",
    vehicleType: "Sedan",
    price: 40,
    seatsLeft: 3,
    avatar: GARDEN_AVATARS[4],
    eta: "12 min",
    badge: "Ladies Only 👩",
    from: "Burnpur Riverside",
    to: "Asansol Market",
    date: new Date().toISOString(),
    time: "11:00",
    rating: 4.9,
  },
  {
    id: "r6",
    hostId: "h6",
    name: "Vikram Singh",
    car: "TVS Apache",
    vehicleType: "Bike",
    price: 35,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[5],
    eta: "8 min",
    badge: "Student 🎓",
    from: "Kulti College",
    to: "Asansol",
    date: new Date().toISOString(),
    time: "14:30",
    rating: 4.5,
  },
  {
    id: "r7",
    hostId: "h7",
    name: "Rakesh Gupta",
    car: "Toyota Innova",
    vehicleType: "SUV",
    price: 150,
    seatsLeft: 5,
    avatar: GARDEN_AVATARS[6],
    eta: "25 min",
    badge: "Family Trip 👨‍👩‍👧‍👦",
    from: "Barakar",
    to: "Dhanbad Station",
    date: new Date().toISOString(),
    time: "07:00",
    rating: 4.8,
  },
  {
    id: "r8",
    hostId: "h8",
    name: "Sneha Sharma",
    car: "Ather 450X",
    vehicleType: "EV Scooty",
    price: 15,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[7],
    eta: "15 min",
    badge: "Green Ride 🌿",
    from: "Neamatpur",
    to: "Asansol Jubilee Park",
    date: new Date().toISOString(),
    time: "16:00",
    rating: 4.7,
  },
  {
    id: "r9",
    hostId: "h9",
    name: "Arjun Yadav",
    car: "Maruti Dzire",
    vehicleType: "Sedan",
    price: 100,
    seatsLeft: 3,
    avatar: GARDEN_AVATARS[8],
    eta: "30 min",
    badge: "AC Cabs ❄️",
    from: "Andal Airport",
    to: "Asansol",
    date: new Date().toISOString(),
    time: "12:00",
    rating: 4.6,
  },
  {
    id: "r10",
    hostId: "h10",
    name: "Manoj Tiwari",
    car: "Bajaj Pulsar",
    vehicleType: "Bike",
    price: 25,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[9],
    eta: "5 min",
    badge: "Fastest 🚀",
    from: "Sitarampur",
    to: "Neamatpur",
    date: new Date().toISOString(),
    time: "18:45",
    rating: 4.4,
  },
  {
    id: "r11",
    hostId: "h11",
    name: "Deepak Mishra",
    car: "Hero Splendor",
    vehicleType: "Bike",
    price: 20,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[10],
    eta: "10 min",
    badge: "Budget 💰",
    from: "Hutton Road",
    to: "Mohishila",
    date: new Date().toISOString(),
    time: "09:30",
    rating: 4.3,
  },
  {
    id: "r12",
    hostId: "h12",
    name: "Sonia Ganguly",
    car: "Hyundai i20",
    vehicleType: "Hatchback",
    price: 55,
    seatsLeft: 2,
    avatar: GARDEN_AVATARS[11],
    eta: "20 min",
    badge: "Comfort 🛋️",
    from: "Durgapur Station",
    to: "Benachity",
    date: new Date().toISOString(),
    time: "19:00",
    rating: 4.8,
  },
  {
    id: "r13",
    hostId: "h13",
    name: "Rohan Sen",
    car: "TVS iQube",
    vehicleType: "EV Scooty",
    price: 18,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[0],
    eta: "12 min",
    badge: "Silent Ride 🤫",
    from: "Ushagram",
    to: "Murgisol",
    date: new Date().toISOString(),
    time: "08:45",
    rating: 4.5,
  },
  {
    id: "r14",
    hostId: "h14",
    name: "Karan Johar",
    car: "Tata Nexon",
    vehicleType: "SUV",
    price: 120,
    seatsLeft: 4,
    avatar: GARDEN_AVATARS[1],
    eta: "40 min",
    badge: "Highway Trip 🛣️",
    from: "Asansol",
    to: "Panagarh",
    date: new Date().toISOString(),
    time: "06:00",
    rating: 4.9,
  },
  {
    id: "r15",
    hostId: "h15",
    name: "Pooja Hegde",
    car: "Honda Activa",
    vehicleType: "Scooty",
    price: 22,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[2],
    eta: "15 min",
    badge: "Verified ✅",
    from: "Kalyanpur",
    to: "Asansol Engineering College",
    date: new Date().toISOString(),
    time: "09:15",
    rating: 4.7,
  },
  {
    id: "r16",
    hostId: "h16",
    name: "Bikram Ghosh",
    car: "Royal Enfield Meteor",
    vehicleType: "Bike",
    price: 40,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[3],
    eta: "20 min",
    badge: "Cruiser 🏍️",
    from: "Rupnarayanpur",
    to: "Chittaranjan Loco",
    date: new Date().toISOString(),
    time: "10:00",
    rating: 4.8,
  },
  {
    id: "r17",
    hostId: "h17",
    name: "Md. Irfan",
    car: "Mahindra Scorpio",
    vehicleType: "SUV",
    price: 90,
    seatsLeft: 6,
    avatar: GARDEN_AVATARS[4],
    eta: "35 min",
    badge: "Group Travel 🚌",
    from: "Raniganj Punjabi More",
    to: "Durgapur Mission Hospital",
    date: new Date().toISOString(),
    time: "13:00",
    rating: 4.5,
  },
  {
    id: "r18",
    hostId: "h18",
    name: "Tanya Dutta",
    car: "Kia Seltos",
    vehicleType: "SUV",
    price: 70,
    seatsLeft: 3,
    avatar: GARDEN_AVATARS[5],
    eta: "25 min",
    badge: "Premium ✨",
    from: "City Centre Durgapur",
    to: "Muchipara",
    date: new Date().toISOString(),
    time: "18:00",
    rating: 4.9,
  },
  {
    id: "r19",
    hostId: "h19",
    name: "Sanjay Singhania",
    car: "Ola S1",
    vehicleType: "EV Scooty",
    price: 20,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[6],
    eta: "8 min",
    badge: "Quick ⚡",
    from: "SB Gorai Road",
    to: "Asansol Station",
    date: new Date().toISOString(),
    time: "20:00",
    rating: 4.6,
  },
  {
    id: "r20",
    hostId: "h20",
    name: "Anita Roy",
    car: "Suzuki Access",
    vehicleType: "Scooty",
    price: 25,
    seatsLeft: 1,
    avatar: GARDEN_AVATARS[7],
    eta: "10 min",
    badge: "Easy Ride 🛵",
    from: "Hutton Road",
    to: "Galaxy Mall",
    date: new Date().toISOString(),
    time: "17:45",
    rating: 4.7,
  }
];